name: 🎨 Design
description: 디자인(UI 및 레이아웃) 추가/수정/삭제가 필요한가요?
title: '[Design]] '
labels: ['🎨 Design']
body:
  - type: textarea
    id: feature-description
    attributes:
      label: 📄 설명
      description: 새로운 디자인에 대한 설명을 작성해 주세요.
      placeholder: 자세하게 작성하기!
    validations:
      required: true
  - type: textarea
    id: feature-todo
    attributes:
      label: ✅ 해야 할 일
      description: 해야 할 일에 대한 Tasks를 작성해 주세요.
      placeholder: 최대한 세분화해서 작성! (체크박스 활용하기)
    validations:
      required: true
  - type: textarea
    id: feature-memo
    attributes:
      label: 📝 메모
      description: 더 하고 싶은 말이 있다면 작성해 주세요.
    validations:
      required: false
